# Generated by Django 5.0.7 on 2024-07-17 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Informacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresasJuinior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=18)),
                ('inscricao_estadual', models.CharField(max_length=20)),
                ('representante_legal', models.CharField(max_length=100)),
                ('cpf_representante_lega', models.CharField(max_length=11)),
                ('area_atuacao', models.CharField(max_length=100)),
                ('site', models.URLField(blank=True)),
                ('fundacao', models.DateField()),
                ('info_contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='juniors.informacoes')),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('periodo_entrada', models.CharField(max_length=50)),
                ('periodo_saida', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('DESLIGADO', 'Desativado')], max_length=9)),
                ('empresa_junior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='juniors.empresasjuinior')),
                ('nome_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='juniors.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('funcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='juniors.funcao')),
                ('historico_membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcoes', to='juniors.membro')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='voluntario_lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lider_departamento', to='juniors.membro'),
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=20)),
                ('status_civil', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('matricula_ies', models.CharField(max_length=20, unique=True)),
                ('informacoes_voluntario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voluntarios', to='juniors.informacoes')),
            ],
        ),
        migrations.AddField(
            model_name='membro',
            name='nome_voluntario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='membros', to='juniors.voluntario'),
        ),
    ]
