# Generated by Django 5.0.7 on 2024-07-17 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juniors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('AB', 'Aberta'), ('FE', 'Fechada'), ('EP', 'Em Processo'), ('PA', 'Pausa')], default='FE', max_length=2)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juniors.funcao')),
            ],
        ),
        migrations.CreateModel(
            name='CandidaturaSimples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('--', 'Análise'), ('AP', 'Aprovado'), ('CR', 'Cadastro reserva')], default='--', max_length=2)),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='juniors.voluntario')),
                ('vaga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='rhselecao.vagas')),
            ],
        ),
    ]
